$(document).ready(function(){
    $('.button-collapse').sideNav();
    $('.parallax').parallax();
    $('.carousel.carousel-slider').carousel();
    $('.slider').slider();
    $('.materialboxed').materialbox();
  $('.material-icons').click(function(){
     $('.overlay-desc').hide();
   });
   $('html').click(function(){
     $('.overlay-desc').show();
   });
});
